# Generated by Django 3.2.2 on 2021-05-15 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текс вопроса')),
                ('type', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='interviews',
            options={'ordering': ['bdate'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterField(
            model_name='interviews',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2021, 5, 15, 15, 42, 3, 9869), verbose_name='дата старта'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='edate',
            field=models.DateField(verbose_name='дата окончание'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='iname',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
