# Generated by Django 3.2.2 on 2021-05-15 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0003_auto_20210515_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mytestapp.interviews'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2021, 5, 15, 15, 54, 3, 682308), verbose_name='дата старта'),
        ),
    ]
