# Generated by Django 3.2.2 on 2021-05-16 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0004_auto_20210515_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2021, 5, 16, 17, 2, 17, 603601), verbose_name='дата старта'),
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('type', models.CharField(default='Not anonym', max_length=50, verbose_name='поля для типа ответа')),
                ('dates', models.DateField(default=datetime.datetime(2021, 5, 16, 17, 2, 17, 604636))),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytestapp.questions')),
            ],
        ),
    ]
