# Generated by Django 3.2.2 on 2021-06-12 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0008_auto_20210612_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='dates',
            field=models.DateField(default=datetime.datetime(2021, 6, 12, 18, 9, 48, 532520)),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2021, 6, 12, 18, 9, 48, 532520), verbose_name='дата старта'),
        ),
    ]
