# Generated by Django 3.1.3 on 2021-06-12 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0009_auto_20210612_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
        migrations.AlterField(
            model_name='answers',
            name='dates',
            field=models.DateField(default=datetime.datetime(2021, 6, 12, 12, 24, 39, 3121)),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2021, 6, 12, 12, 24, 39, 2122), verbose_name='дата старта'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='mytestapp.interviews'),
        ),
    ]
